version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t ksironov/docker-react -f Dockerfile.dev .
      - run:
          name: Run Tests
          command: docker run ksironov/docker-react npm run test -- --coverage

workflows:
  build-and-test:
    jobs:
      - build
